# Generated by Django 6.0.4 on 2026-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("audio_file", models.FileField(upload_to="songs/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="song_covers/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
