# Generated by Django 6.0.4 on 2026-04-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_album_photo_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="album",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
    ]
