# Generated by Django 6.0.4 on 2026-04-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_remove_photo_album_remove_photo_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="title",
        ),
    ]
