# Generated by Django 6.0.4 on 2026-04-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_photo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
